run:
  timeout: 5m
  go: '1.25'
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - staticcheck
    - errcheck
    - gosimple
    - ineffassign
    - unused
    - typecheck
    - bodyclose
    - exportloopref
    - gosec
    - misspell
    - revive

linters-settings:
  goimports:
    local-prefixes: hateblog

  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck

  gosec:
    excludes:
      - G404  # Use of weak random number generator (math/rand) - ok for non-security use

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests
    - path: _test\.go
      linters:
        - gosec
        - errcheck
