# Development overrides
# This file is automatically loaded by Docker Compose in development
# For production, this file should not be present

services:
  postgres:
    ports:
      - "5432:5432" # Expose to host for local tools

  redis:
    ports:
      - "6379:6379" # Expose to host for local tools

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sleep infinity
    restart: "no"
    user: "1000:1000"
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    env_file:
      - .env
