// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusHealthy   HealthResponseStatus = "healthy"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for RankingResponsePeriodType.
const (
	RankingResponsePeriodTypeMonthly RankingResponsePeriodType = "monthly"
	RankingResponsePeriodTypeWeekly  RankingResponsePeriodType = "weekly"
	RankingResponsePeriodTypeYearly  RankingResponsePeriodType = "yearly"
)

// Defines values for GetClickedTagsParamsDays.
const (
	GetClickedTagsParamsDaysN1  GetClickedTagsParamsDays = 1
	GetClickedTagsParamsDaysN30 GetClickedTagsParamsDays = 30
	GetClickedTagsParamsDaysN7  GetClickedTagsParamsDays = 7
)

// Defines values for GetTrendingTagsParamsHours.
const (
	GetTrendingTagsParamsHoursN12 GetTrendingTagsParamsHours = 12
	GetTrendingTagsParamsHoursN24 GetTrendingTagsParamsHours = 24
	GetTrendingTagsParamsHoursN48 GetTrendingTagsParamsHours = 48
	GetTrendingTagsParamsHoursN6  GetTrendingTagsParamsHours = 6
)

// ApiKeyResponse APIキー発行レスポンス
type ApiKeyResponse struct {
	// CreatedAt 作成日時
	CreatedAt time.Time `json:"created_at"`

	// Description キーの説明
	Description *string `json:"description"`

	// ExpiresAt 有効期限
	ExpiresAt *time.Time `json:"expires_at"`

	// Id APIキーID
	Id openapi_types.UUID `json:"id"`

	// Key 生成されたAPIキー（この1回のみ表示）
	Key string `json:"key"`

	// Name キーの名前
	Name *string `json:"name"`
}

// ArchiveItem 日別エントリー数
type ArchiveItem struct {
	// Count その日のエントリー件数
	Count int `json:"count"`

	// Date 日付（YYYY-MM-DD形式）
	Date openapi_types.Date `json:"date"`
}

// ArchiveResponse 日別エントリー数一覧レスポンス
type ArchiveResponse struct {
	// Items 日別エントリー数一覧（日付降順）
	Items []ArchiveItem `json:"items"`
}

// ClickMetricsRequest クリック計測リクエスト
type ClickMetricsRequest struct {
	// EntryId エントリーID
	EntryId openapi_types.UUID `json:"entry_id"`

	// Referrer リファラーURL（オプション）
	Referrer *string `json:"referrer"`

	// UserAgent ユーザーエージェント（オプション）
	UserAgent *string `json:"user_agent"`
}

// ClickedTag クリックされたタグ（クリック数付き）
type ClickedTag struct {
	// ClickCount 集計期間内でのクリック数
	ClickCount int `json:"click_count"`

	// EntryCount このタグに紐づく総エントリー数
	EntryCount int `json:"entry_count"`

	// Id タグID
	Id openapi_types.UUID `json:"id"`

	// Name タグ名
	Name string `json:"name"`
}

// ClickedTagsResponse クリックされたタグ一覧レスポンス
type ClickedTagsResponse struct {
	// Days 集計対象日数
	Days int `json:"days"`

	// Tags クリックされたタグ一覧
	Tags []ClickedTag `json:"tags"`

	// Total 該当タグ総数
	Total int `json:"total"`
}

// CreateApiKeyRequest APIキー発行リクエスト
type CreateApiKeyRequest struct {
	// Description キーの説明（オプション）
	Description *string `json:"description"`

	// ExpiresAt 有効期限（オプション、将来の拡張用）
	ExpiresAt *time.Time `json:"expires_at"`

	// Name キーの名前（オプション、将来の管理用）
	Name *string `json:"name"`
}

// Entry はてなブックマークエントリー
type Entry struct {
	// BookmarkCount はてなブックマーク件数
	BookmarkCount int `json:"bookmark_count"`

	// CreatedAt レコード作成日時（ISO 8601形式）
	CreatedAt time.Time `json:"created_at"`

	// Excerpt 記事本文の抜粋
	Excerpt *string `json:"excerpt"`

	// FaviconUrl Favicon URL（FaviconプロキシAPI）
	FaviconUrl *string `json:"favicon_url,omitempty"`

	// Id エントリーID
	Id openapi_types.UUID `json:"id"`

	// PostedAt 記事の投稿日時（ISO 8601形式）
	PostedAt time.Time `json:"posted_at"`

	// Subject RSSフィードのsubject（画面非表示、内部利用）
	Subject *string `json:"subject"`

	// Tags エントリーに紐づくタグ一覧
	Tags []EntryTag `json:"tags"`

	// Title エントリーのタイトル
	Title string `json:"title"`

	// UpdatedAt レコード更新日時（ISO 8601形式）
	UpdatedAt time.Time `json:"updated_at"`

	// Url エントリーのURL
	Url string `json:"url"`
}

// EntryListResponse エントリー一覧レスポンス
type EntryListResponse struct {
	// Entries エントリー一覧
	Entries []Entry `json:"entries"`

	// Limit 1ページあたりの件数
	Limit int `json:"limit"`

	// Offset オフセット
	Offset int `json:"offset"`

	// Total 総件数（フィルタ適用後）
	Total int `json:"total"`
}

// EntryTag エントリーに紐づくタグ（スコア付き）
type EntryTag struct {
	// Score タグのスコア（Yahoo! キーフレーズ抽出APIから取得した重要度、0〜100）
	Score int `json:"score"`

	// TagId タグID
	TagId openapi_types.UUID `json:"tag_id"`

	// TagName タグ名
	TagName string `json:"tag_name"`
}

// ErrorResponse エラーレスポンス
type ErrorResponse struct {
	// Details 詳細情報（オプション）
	Details *map[string]interface{} `json:"details"`

	// Error エラーコード
	Error string `json:"error"`

	// Message エラーメッセージ
	Message string `json:"message"`
}

// HealthResponse ヘルスチェックレスポンス
type HealthResponse struct {
	// Database データベース接続状態
	Database *struct {
		// Connected 接続可否
		Connected *bool `json:"connected,omitempty"`

		// ResponseTimeMs レスポンスタイム（ミリ秒）
		ResponseTimeMs *float32 `json:"response_time_ms,omitempty"`
	} `json:"database,omitempty"`

	// Status ステータス
	Status HealthResponseStatus `json:"status"`

	// Timestamp チェック実行日時
	Timestamp time.Time `json:"timestamp"`
}

// HealthResponseStatus ステータス
type HealthResponseStatus string

// MetricsResponse メトリクス記録レスポンス
type MetricsResponse struct {
	// Message メッセージ
	Message string `json:"message"`

	// Success 成功フラグ
	Success bool `json:"success"`
}

// RankingEntry ランキングエントリー
type RankingEntry struct {
	// Entry はてなブックマークエントリー
	Entry Entry `json:"entry"`

	// Rank 順位
	Rank int `json:"rank"`
}

// RankingResponse ランキングレスポンス
type RankingResponse struct {
	// Entries ランキングエントリー一覧
	Entries []RankingEntry `json:"entries"`

	// Month 対象月（月次・週次ランキング時のみ）
	Month *int `json:"month"`

	// PeriodType ランキング期間種別
	PeriodType RankingResponsePeriodType `json:"period_type"`

	// Total 対象期間の総エントリー数
	Total int `json:"total"`

	// Week 対象週（週次ランキング時のみ、ISO週番号）
	Week *int `json:"week"`

	// Year 対象年
	Year int `json:"year"`
}

// RankingResponsePeriodType ランキング期間種別
type RankingResponsePeriodType string

// SearchResponse 検索結果レスポンス
type SearchResponse struct {
	// Entries 検索結果のエントリー一覧
	Entries []Entry `json:"entries"`

	// Limit 1ページあたりの件数
	Limit int `json:"limit"`

	// Offset オフセット
	Offset int `json:"offset"`

	// Query 検索キーワード
	Query string `json:"query"`

	// Total 検索結果の総件数
	Total int `json:"total"`
}

// TrendingTag トレンドタグ（出現回数付き）
type TrendingTag struct {
	// EntryCount このタグに紐づく総エントリー数
	EntryCount int `json:"entry_count"`

	// Id タグID
	Id openapi_types.UUID `json:"id"`

	// Name タグ名
	Name string `json:"name"`

	// OccurrenceCount 集計期間内での出現回数（エントリー数）
	OccurrenceCount int `json:"occurrence_count"`
}

// TrendingTagsResponse トレンドタグ一覧レスポンス
type TrendingTagsResponse struct {
	// Hours 集計対象時間
	Hours int `json:"hours"`

	// Tags トレンドタグ一覧
	Tags []TrendingTag `json:"tags"`

	// Total 該当タグ総数
	Total int `json:"total"`
}

// UnauthorizedError エラーレスポンス
type UnauthorizedError = ErrorResponse

// GetArchiveParams defines parameters for GetArchive.
type GetArchiveParams struct {
	// MinUsers 最低ブックマーク件数フィルタ
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`
}

// GetHotEntriesParams defines parameters for GetHotEntries.
type GetHotEntriesParams struct {
	// Date 取得対象日付（YYYYMMDD形式）
	Date string `form:"date" json:"date"`

	// MinUsers 最低ブックマーク件数（5/10/50/100/500/1000など）
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset オフセット（ページネーション用）
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetNewEntriesParams defines parameters for GetNewEntries.
type GetNewEntriesParams struct {
	// Date 取得対象日付（YYYYMMDD形式）
	Date string `form:"date" json:"date"`

	// MinUsers 最低ブックマーク件数（5/10/50/100/500/1000など）
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset オフセット（ページネーション用）
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetFaviconParams defines parameters for GetFavicon.
type GetFaviconParams struct {
	// Domain Faviconを取得するドメイン名
	Domain string `form:"domain" json:"domain"`
}

// GetMonthlyRankingParams defines parameters for GetMonthlyRanking.
type GetMonthlyRankingParams struct {
	// Year 対象年（YYYY形式）
	Year int `form:"year" json:"year"`

	// Month 対象月（MM形式、1-12）
	Month int `form:"month" json:"month"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetWeeklyRankingParams defines parameters for GetWeeklyRanking.
type GetWeeklyRankingParams struct {
	// Year 対象年（YYYY形式）
	Year int `form:"year" json:"year"`

	// Week 対象週（1-53、ISO週番号）
	Week int `form:"week" json:"week"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetYearlyRankingParams defines parameters for GetYearlyRanking.
type GetYearlyRankingParams struct {
	// Year 対象年（YYYY形式）
	Year int `form:"year" json:"year"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchEntriesParams defines parameters for SearchEntries.
type SearchEntriesParams struct {
	// Q 検索キーワード
	Q string `form:"q" json:"q"`

	// MinUsers 最低ブックマーク件数フィルタ
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset オフセット（ページネーション用）
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetClickedTagsParams defines parameters for GetClickedTags.
type GetClickedTagsParams struct {
	// Days 集計対象日数（デフォルト 7日間）
	Days *GetClickedTagsParamsDays `form:"days,omitempty" json:"days,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetClickedTagsParamsDays defines parameters for GetClickedTags.
type GetClickedTagsParamsDays int

// GetTrendingTagsParams defines parameters for GetTrendingTags.
type GetTrendingTagsParams struct {
	// Hours 集計対象時間（デフォルト 24時間）
	Hours *GetTrendingTagsParamsHours `form:"hours,omitempty" json:"hours,omitempty"`

	// MinUsers 対象エントリーの最低ブックマーク件数
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTrendingTagsParamsHours defines parameters for GetTrendingTags.
type GetTrendingTagsParamsHours int

// GetEntriesByTagParams defines parameters for GetEntriesByTag.
type GetEntriesByTagParams struct {
	// MinUsers 最低ブックマーク件数（5/10/50/100/500/1000など）
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset オフセット（ページネーション用）
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// RecordClickJSONRequestBody defines body for RecordClick for application/json ContentType.
type RecordClickJSONRequestBody = ClickMetricsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// APIキー発行
	// (POST /api-keys)
	CreateApiKey(w http.ResponseWriter, r *http.Request)
	// 日別エントリー数一覧取得
	// (GET /archive)
	GetArchive(w http.ResponseWriter, r *http.Request, params GetArchiveParams)
	// 人気順エントリー一覧取得
	// (GET /entries/hot)
	GetHotEntries(w http.ResponseWriter, r *http.Request, params GetHotEntriesParams)
	// 新着順エントリー一覧取得
	// (GET /entries/new)
	GetNewEntries(w http.ResponseWriter, r *http.Request, params GetNewEntriesParams)
	// Faviconプロキシ
	// (GET /favicons)
	GetFavicon(w http.ResponseWriter, r *http.Request, params GetFaviconParams)
	// ヘルスチェック
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// クリック計測
	// (POST /metrics/clicks)
	RecordClick(w http.ResponseWriter, r *http.Request)
	// 月次ランキング取得
	// (GET /rankings/monthly)
	GetMonthlyRanking(w http.ResponseWriter, r *http.Request, params GetMonthlyRankingParams)
	// 週次ランキング取得
	// (GET /rankings/weekly)
	GetWeeklyRanking(w http.ResponseWriter, r *http.Request, params GetWeeklyRankingParams)
	// 年次ランキング取得
	// (GET /rankings/yearly)
	GetYearlyRanking(w http.ResponseWriter, r *http.Request, params GetYearlyRankingParams)
	// キーワード検索
	// (GET /search)
	SearchEntries(w http.ResponseWriter, r *http.Request, params SearchEntriesParams)
	// クリックされたエントリーのタグ一覧取得
	// (GET /tags/clicked)
	GetClickedTags(w http.ResponseWriter, r *http.Request, params GetClickedTagsParams)
	// トレンドタグ一覧取得
	// (GET /tags/trending)
	GetTrendingTags(w http.ResponseWriter, r *http.Request, params GetTrendingTagsParams)
	// タグ別エントリー一覧取得
	// (GET /tags/{tag}/entries)
	GetEntriesByTag(w http.ResponseWriter, r *http.Request, tag string, params GetEntriesByTagParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// APIキー発行
// (POST /api-keys)
func (_ Unimplemented) CreateApiKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 日別エントリー数一覧取得
// (GET /archive)
func (_ Unimplemented) GetArchive(w http.ResponseWriter, r *http.Request, params GetArchiveParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人気順エントリー一覧取得
// (GET /entries/hot)
func (_ Unimplemented) GetHotEntries(w http.ResponseWriter, r *http.Request, params GetHotEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 新着順エントリー一覧取得
// (GET /entries/new)
func (_ Unimplemented) GetNewEntries(w http.ResponseWriter, r *http.Request, params GetNewEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Faviconプロキシ
// (GET /favicons)
func (_ Unimplemented) GetFavicon(w http.ResponseWriter, r *http.Request, params GetFaviconParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ヘルスチェック
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// クリック計測
// (POST /metrics/clicks)
func (_ Unimplemented) RecordClick(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 月次ランキング取得
// (GET /rankings/monthly)
func (_ Unimplemented) GetMonthlyRanking(w http.ResponseWriter, r *http.Request, params GetMonthlyRankingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 週次ランキング取得
// (GET /rankings/weekly)
func (_ Unimplemented) GetWeeklyRanking(w http.ResponseWriter, r *http.Request, params GetWeeklyRankingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 年次ランキング取得
// (GET /rankings/yearly)
func (_ Unimplemented) GetYearlyRanking(w http.ResponseWriter, r *http.Request, params GetYearlyRankingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// キーワード検索
// (GET /search)
func (_ Unimplemented) SearchEntries(w http.ResponseWriter, r *http.Request, params SearchEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// クリックされたエントリーのタグ一覧取得
// (GET /tags/clicked)
func (_ Unimplemented) GetClickedTags(w http.ResponseWriter, r *http.Request, params GetClickedTagsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// トレンドタグ一覧取得
// (GET /tags/trending)
func (_ Unimplemented) GetTrendingTags(w http.ResponseWriter, r *http.Request, params GetTrendingTagsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タグ別エントリー一覧取得
// (GET /tags/{tag}/entries)
func (_ Unimplemented) GetEntriesByTag(w http.ResponseWriter, r *http.Request, tag string, params GetEntriesByTagParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArchive operation middleware
func (siw *ServerInterfaceWrapper) GetArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArchiveParams

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArchive(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHotEntries operation middleware
func (siw *ServerInterfaceWrapper) GetHotEntries(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHotEntriesParams

	// ------------- Required query parameter "date" -------------

	if paramValue := r.URL.Query().Get("date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "date", r.URL.Query(), &params.Date)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHotEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNewEntries operation middleware
func (siw *ServerInterfaceWrapper) GetNewEntries(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNewEntriesParams

	// ------------- Required query parameter "date" -------------

	if paramValue := r.URL.Query().Get("date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "date", r.URL.Query(), &params.Date)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNewEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFavicon operation middleware
func (siw *ServerInterfaceWrapper) GetFavicon(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFaviconParams

	// ------------- Required query parameter "domain" -------------

	if paramValue := r.URL.Query().Get("domain"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "domain"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "domain", r.URL.Query(), &params.Domain)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "domain", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFavicon(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordClick operation middleware
func (siw *ServerInterfaceWrapper) RecordClick(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordClick(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMonthlyRanking operation middleware
func (siw *ServerInterfaceWrapper) GetMonthlyRanking(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMonthlyRankingParams

	// ------------- Required query parameter "year" -------------

	if paramValue := r.URL.Query().Get("year"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "year", r.URL.Query(), &params.Year)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		return
	}

	// ------------- Required query parameter "month" -------------

	if paramValue := r.URL.Query().Get("month"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "month"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "month", r.URL.Query(), &params.Month)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMonthlyRanking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWeeklyRanking operation middleware
func (siw *ServerInterfaceWrapper) GetWeeklyRanking(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWeeklyRankingParams

	// ------------- Required query parameter "year" -------------

	if paramValue := r.URL.Query().Get("year"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "year", r.URL.Query(), &params.Year)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		return
	}

	// ------------- Required query parameter "week" -------------

	if paramValue := r.URL.Query().Get("week"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "week"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "week", r.URL.Query(), &params.Week)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "week", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWeeklyRanking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetYearlyRanking operation middleware
func (siw *ServerInterfaceWrapper) GetYearlyRanking(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetYearlyRankingParams

	// ------------- Required query parameter "year" -------------

	if paramValue := r.URL.Query().Get("year"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "year", r.URL.Query(), &params.Year)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetYearlyRanking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchEntries operation middleware
func (siw *ServerInterfaceWrapper) SearchEntries(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchEntriesParams

	// ------------- Required query parameter "q" -------------

	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetClickedTags operation middleware
func (siw *ServerInterfaceWrapper) GetClickedTags(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClickedTagsParams

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameter("form", true, false, "days", r.URL.Query(), &params.Days)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "days", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClickedTags(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrendingTags operation middleware
func (siw *ServerInterfaceWrapper) GetTrendingTags(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrendingTagsParams

	// ------------- Optional query parameter "hours" -------------

	err = runtime.BindQueryParameter("form", true, false, "hours", r.URL.Query(), &params.Hours)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hours", Err: err})
		return
	}

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrendingTags(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEntriesByTag operation middleware
func (siw *ServerInterfaceWrapper) GetEntriesByTag(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tag" -------------
	var tag string

	err = runtime.BindStyledParameterWithOptions("simple", "tag", chi.URLParam(r, "tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEntriesByTagParams

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntriesByTag(w, r, tag, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api-keys", wrapper.CreateApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/archive", wrapper.GetArchive)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/entries/hot", wrapper.GetHotEntries)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/entries/new", wrapper.GetNewEntries)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/favicons", wrapper.GetFavicon)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/metrics/clicks", wrapper.RecordClick)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rankings/monthly", wrapper.GetMonthlyRanking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rankings/weekly", wrapper.GetWeeklyRanking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rankings/yearly", wrapper.GetYearlyRanking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search", wrapper.SearchEntries)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags/clicked", wrapper.GetClickedTags)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags/trending", wrapper.GetTrendingTags)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags/{tag}/entries", wrapper.GetEntriesByTag)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xde3PTSLb/Kr66+6cdy44dIFW3bmUXdiY1k4EKzN3LMtysYncSDbbkkWQgS6XKkng4",
	"JJlkAwQCgRAgDxJIwsBAXpAP05Eff+Ur3OpuSZbklh9ZXvduqqaIE0vdp0+f8zvP7rnCJMR0RhSAoMhM",
	"+xVGAnJGFGSAf/lR4LLKgCjxfwfJE5IkSuiPCVFQgKCgj1wmk+ITnMKLQvhnWRTQ38BlLp1JAfyRvML8",
	"+EPHj2e+Pdnd+dcTx5kgkwayzPUDpp3pFC5yKT4ZEKVAmpdlXugPdJzqDFwAg8xQkJETAyDNoYH+IIE+",
	"pp3593CF1jD5Vg5jurpNqpmhoaEgkwRyQuIziCymnSktj5WWdqC2BPXnUN8JhNAcUHsJ9R2ojhavzhk3",
	"N6H6AaqzUF0rzCwXxif2PjxghmwKMCs6Mvx3YNCep/2KZxZ7zOL0VmluFOovoLYJ9YdQfw21TSbIZCQx",
	"AySFJ5xNSIBTQLKHU6qH2ns/U8hPFO7OF6Y1JlhhKBNlo/EQGwmx8TMRtp1F//2VCTJ9opRG4zBJTgEh",
	"hU8DJsgogxn0iqxIvNDPeJnindJix2pp+UXh3q+uWQszL4p3louT68YTHaqrUL8D9ZdoWXoeM/U11Ieh",
	"9gTqd6G+XLy9xAQZIZtKcb3obUXKAgox4HKGl4BMXX5hZti4uVmYmS1PT3iX3xaKREOtkTPR1vb4sfb4",
	"Md/l16WAT9bYw87jromP9R0FR5JtiVC8N8aFWhPRZCgC2L5QJNoai7cdOXqM6004Cclm+SRtC5BcV01a",
	"vD1byE9A9Q7URqE6a9Owv5OH6i2orkaMB48Q39Xd0txS8dnW/s6wi7qB3p4UfxH02NSwXG8iCfq8v9Mo",
	"Erg0qCENxsSYMTzmmu3PElb/ZKAjkwl8Bwbr83ooyEjglywvgSTTfo7BrLmAX3QowXn7NbH3Z5BQEHEd",
	"UmKAvwg6FZCmSMndeSM/bwlgHurLUN8p3Fmv1jQxK1CkDKoPobpauDuPWOseZW/7LRnIXjViZZBJ8wKf",
	"zqaZdtYmlhcU0A8krF+cAqhk7m3f29/Jnz179myoqyt0/Ljx/omxM+7dxYpue0WaqcdR8yGy0BqM9Acv",
	"P2bubeRKC4v1sIxXQFpudtD9nTzhTXl6rPz4OmGHPVItwHeKxZC9Wk6SuMFqYcMD0njypxSfuNAFFIlP",
	"yN3glyyQaUKirWGydaitlZbyhY0X6FdtDS0KcSRfxQsgKNJgDw1cPIzwQEw8zoKjMZYNgeix3lAskoyF",
	"uCORtlAs1tYWj8diLMuyjUCMBPqAJAGJMj+a9g7U5ogZ/LH7e4Qw2jLCbe0d1Beh/roKWhQlI7eHwwOc",
	"AnpTYn+L+VVLQkyH0VJ5IIcFcKkRwM3KQOrh+gFVGfUFBDjaW/zvEv53A2qLhGH16ewS/86nUlw43sK2",
	"tLQ0DUn2pvkKCkie4fpry4eN4FDbhdo6JrryLZL77XtQHSOkeyAKTdHjA1TlB9eR6M3MlqduGdevQXUR",
	"I5ZraBdWxdvqQRVZry8w3sIToEVAdaX4ZgKq81AdL74bp6JtUyBJVww0lUcfItFWgKxXCBw91huKRJOt",
	"IS4WbwvFom1tkVjkSKxBffAzcGhKY8Jt2r4RkXPKXf4eCP3KANMeYdmGjBmeI+jaRTePa4uV7I/LNeSr",
	"MWhOcoOyn0gZax9Kr+aQm+nexyO0jVO4fvkA9DWK6Q4lq4L0IKOICpeqnr30/Dfj/S0yXfHduGcZrWxt",
	"YfTsJF5gkDDMmpG6b9hnsaIBH7tRFQzUNhrNuOb1wfAA/rpD6ONI6D+a/15NLcypxvr1wkPkdxVG5oyd",
	"34u3lyjO0Mfz9BvycWsTWlydK05cpxBK8Ya9AFLfFFXJ2AmEHTRkXoPqAlSXoT5l6pz+CNvKNQ8yV0lY",
	"ryheSHPSBX/Q9x2a4g3H2Xo4Xyu8xZj1Gg2uDztD3f2dfOfpk4GjbWyknot8gPAXXE4AKUMhp7R0b29r",
	"pDDzojB1A8nkzZnibyMeu1BaypWWH0Ftcu/9LlSfQnX2L6A30HGqszw1UpzeQlK0Olt693vx/lXMw+uY",
	"gSMmJ7XJ4pvNve0RqN7FeYbphnyUINPHXeQTotCTlSjg92fyZYD4ceZvWKdfItHW3nWc6vQyMMxl+PDF",
	"SNgcWP7PpJjmeOE/HF6dy6ZKPNNg5Px5nNuMKPsJFdlFvH93iku7B5Ko1uYkSs4Sha2ipfv0aexpPyUy",
	"DtVV89H9nXzx9nb54ZPyw0cklkcgc/1aWV8y8s8p8GJJ0q94VzeIZteVGz9b7doip2vnsdj2/OeuMHJC",
	"lADTfiyOh8WBTaO+GXqeYC/yrIaC9mBHnYNF6w8WcQ9mCfk6DmRmseezzgydb9DVwODq52jwSgo0wDri",
	"Hj/Df1mhY4W6ArU81EbKK/fKuVmoLrsQgyZP2UyyIcwsPHhTmFo/gIRHm8VMKvBUM+PH7u+pUaMzWOQk",
	"hU+kQLhfTHFCf+gS6A1xGb4u2tDcbbJJhDonJgS9Vi5oOXUOa+Ri83k/2/s9Lyu1vHJ3uqghT9yMlhsc",
	"jWlGmGmSnOLTPEWOIlC/b0bXqoZ99ZtQXa028dE4zaqLfX0yoKZJSGphGxk87N/aA1G9Ax9/vvhunFCC",
	"nDETQFegtltWETYaH0Y9wo1d1SZcfGsLLAIsLtkL85UHn+C/DqBin3IT6a32xD/4N0GRHqJiqDGH2N/J",
	"n+UGRPHfAqbvihz7F3g3two33xs3tlDYoY5AbdgYnzI+3MX+xmz5xlhpQTW2FmBOZWFuJsKyHj4icE9z",
	"lwkbI2xd587C7s8ayFcMwCcL5s11OeYKmrtDFQxX3YkuHc/xNtUJ0YHC8Sn8kUsmefQ6lzrleIRYeW/o",
	"+7r4Zr2gXzMev6obEeKSnaxIHI9cfyYtCspAIJ2VlUAvCERCkSjiPw9SyUrC+SKXylrmI9LKRnAcRfc7",
	"KhwBVoXQjxOWBXNt1H91fN95vONM58kfek50d5/spm2+XTGsweU57G1vE3RzzWBVGTOcxKWBAqT2AFpm",
	"gMiczYmzZ8+e7eo6fryuFSLrrFBFk45vAZdSBmqIh34Pg9sm1FWc6CQxV71sjsL1cvThbuCF70J9Gn/Y",
	"LPw6X3x7v3jzbeHaCKUmIgggoQCKEpP3jPE1Y2LByUXXnveKYgpwAkk4kyX2ICeih1YH8KzKcp0eY5Sf",
	"hfpycXHSi+wtUQck9KVEbLnNyYVsutdE9yq2ywqnZKlGdhP50oRFmLNAQPh2jhnAG4UC96xgfT7v8mbs",
	"B6oxiU8DWeHSGdqiK9uKYsO50Y9bz/WIpLluJ0k0qbTrHf5iOWcaNBS3bpaW7pVHf6snlv7aWUMpccYv",
	"IIGEKCVBMiBnEwkgy33ZVGqQHmzh7ynymp8wbs5iW/gcxQF1RdbLOXPg2urczQkXeKHfLzGDIOg1tsoo",
	"FqmXjAHWKA15dhInXKCkcB9f33vvsngRh9mO1PWF8KhmlrrWimuJinvRB/Z/azKvOXfYtU0UrxibvmoS",
	"zEz4TH5/J1+YyRdezEF9u5x7hT+4qCtMa6QU7wGsSNTXPjocpwyQeDHZQ76owwdS8CkurRr5eQdcDQJO",
	"whqCl4I/XQLgQsoDWpVvq0GL7nxbPECzQnW1frWHZet7iog0v6nKOeS51OYyzKmdp0+Wc6+Kd5aN8Xde",
	"pjfCc8QwPxKMzTeuoIelhT0exXHuoTl6sCqyoCnUacBJiRoeQeHZTPHNk+LvE4VHMwdWJtcg1Y0N/wKx",
	"5S9ZQINowhgrcFqj+KFW5qYJnfFw245fPVXRpoJUQn/wYMHqGQkISV7op8erSAxeWPUfM0A1bmwVxz8Y",
	"Dx7VLFAfFowPHGMGGTGRyEoSEBKgqRK/c2dwiOdlpQcNY9Gm5MxZua6isH752iFpNd1Jr8g1liwbELNS",
	"vbr1tFaeuuXClVgThWsfwhrFRqeifayCdfxABWvCKn/Dg3xnkMhKvDJ4GhEPHN2sHVmaN9RxqtNqmcVo",
	"mdNILdl4Nly4sw7VxdLSS2P1vqPeTyqpS8Vri8ZE3q5ywZz2k4DjXB3qOZIhC/ztv0MdpzpD34HB9sCg",
	"mJVCXIYPXQCDfwtAbdKYWIGaCtUFT8EcD7kA1XGoPkbTqlfx2GizBBKhJYFkiXM7Y09R0W8Or5d0B/NC",
	"n2j1MXOkfmO++K3Z5hQ4A7h0Vc8sY3VBBbAKjkB9Hpu7J1BfKQ7ncal9wir5mXV23M68t32nsHiv8GCD",
	"cKRGFbfKYpMMD9QmSVMy4qo20n3i9Bncw4xwYtpiRYpPAFMJzeV0dZ4x0+SVnLyYAYIsZqUEaBGl/rD5",
	"khxGz1YKIBVO/JFLXMD17VOdTJC5CCTZNPYtbAuL0S0DBC7DM+1Mawvb0opUmVMGsJCFzb3Fv2REWqNE",
	"YWodb+7VSku2Nmk2TbjkCEHhzBJU10zRVJfx94vWs4tQHTMfV0ft0j2ux65Y0nyVPGzk35anJ6A2Wdp9",
	"b9x8vLeVx9Ls5CXCItzV3plEoaqj5YMhSghk5Y9icrCBdvjGmthpXSVDbo1HDq4j34KZGmUjH40ET4M7",
	"pZHe09VCIm8kAzGW/Whk1G3nx0q2bCW8rGYNKw+IyIl/VnK037EzOWG1LhIqHLDLtJ87H2TkbDrNIc/U",
	"y0arTNV+juGSaV5gzqOXwxzpckX09dP8YuPakh2s+XXaQm0SIynCUFIehOqiozZgaxfpxEUjWfpYfnwd",
	"qit7GwtQfe14sEo3vgGK2Y+LNd9MsMq4duxtC8rtvf/Vr7/EWe+xcN1yhU04S/NCT1YG2NpVNi8J+rhs",
	"SmHa405TWseSnq/So48nMd5ma4rMfLWaEyN4QpvF5le4+lDQV6RztpbV7j4nSuBUPVOIifJZrc0DouKr",
	"gIXRG8bqfVtzvNVAbXJva6uwfhf3tufdlenA8ROn/xQM2KVr/Pv+zrCPdvrqDI4TylMfjNwzp/5gCnAu",
	"TR01xtdK+vta1u0boHwrKifscLOmEhPy7M7RytGGri73wQaaApu1JbdJc+qyOzPORvBZiAynKEBCw/3P",
	"Tz8lrxwd+gMtG94c2uzv5OPhCBuOs+EIi37gnyz2Kp77L6AZBKrrzNNZaycQaPNbGQDK3NG4J8PiU9CN",
	"NEKKJ+eCCzVWakcfc6KH3bNEI9dMVFDpZd15nC+G1tXtHod4/UXw2kZLas6yCq+t9JgbrwVw6eB4XZha",
	"Lz7MEbz+aqD5B3DpEJo/LjRHDqH5EJoPobkJV9oCxoNAs9VrXgeXK9lEfRjqc7hD5DVUV63Gdm2SBr/f",
	"iGJ/CgSsXviOU53F30eLt1+50Dqn4nD7KYabd1CfJ+nE0u5t92A0+DVHroe91VROQ23EuRRSOqBCL+7B",
	"bxB8fTr1B0RZMXP5Xvitr6F8musH4YzQ7xYre/BeXuCkQWoLCnn1cgjzqMm3fVSZ9Mgb+jhO0N2G6jRC",
	"sUP9/oT6TTk84lDnrMKneKWi0KQfyledcXbLMae6VN2bBtVVQ503ri0Vcos4R+VogXOoZJVCkqa6Pw2A",
	"xAXmExoeT+8eTVRfPjU2Nr7K1GfrZ2SDtdG3oLZJDrDsbYwZ42s105/UzkeHvMmDsgLSprClScNaGJ+t",
	"rVFHqOrF3vAckkZoQprZvIlPIz9P6opQXSRHeM1JzYZB5KeuQHVlb/eh8fKeZaf8rUY3bmnD7W2fqlhA",
	"ubrgMxcLvI2EtGt3MLsP/bNPj9/Vt1Q41MkUZlOfJNIgJ4etBrHaXpmx+aYwk4fqamEmX5665WnTOnPy",
	"VCDCsj6+mV+At7dxc+/9WBP1hS5CqtnbVzcMtjq7zOi3XuRrdnA14HyR9jA7eDt27NgxR3QUZdnGYklH",
	"r2FXl1mVyamRUCRaI7rFfYsNURmJOgPMaLPx5T8X6uKA1tki2FSw+ymDSW8762Eo+WVCSbO71oUjVRGk",
	"hVJe0DI7XetiFunehepqOffqi8HWXzCx/69Qi7TsRkLxVmpjLo1Q3AHcGHA5qIy3HuLWIW59RbhFbVNv",
	"GLfMpv36uKWuwtyo2SCGcGgbp3vJh7f432dQf4ab8saqzk18Wjg7i9fwNcBZ7CPA2adEi0O4+JeHCxQ3",
	"NQ0XMj4g4osStS+hgPo2ubkGo8QuAQTPcQfzDIQLH4xrS4WpG+Sb/Z18pr+nl+9P7+8Mk8tuireX6iTJ",
	"ybGWBmuUfqcwaAr4S4Mpcce5De81VmlesFvz/+nC5OftUDusQX4VNUjPoa1DOP1CCS4KjjlTxgQ5CYyi",
	"P5J8MTneTu+eXZ0t33+AL+mh3mDogdpFCwrJAwtQvQq1EfuKDvNQC90D888po+e14rVFs0jpvAMVXyiG",
	"KVwt5fPGP16Xp54Yuzp+Zaxw7zG52sMG+oZqmY4bJ+vhdPUFkVjJb2C1f47NTT5wpHB3vjx1q1ZTyaAP",
	"Eh6xD7RGgkeCrez52tdPfnQ0ZF2nPr+aYI92J+gh5HzxnLo/Lqw6z45V+Xf4pwOUFPPQmC8qFR+8Ke3+",
	"AwEKbob7qDBktr/hU3P4jCGlA44oPELFnGqPSs4hlh9vG1sLUF2yryOC2qRVN2u4ncJ5arApDMJkUzAo",
	"GrO+8gMh63wcDQZiNgy1BSPRYDQWjB09X+dEoV9urFo2aruT/wf72L5S1KQeRT2EzS8Dmz7nauti4xWF",
	"6x8KO+41aKhXrOrMeY2u3s/RwUsIKk/9hnBYXXNyzFDfQHWxdGPZGLljHks0+xEqDQX7O3mF6++5yINL",
	"PQO8rIjSoNNhRFG5H7KaAfgf8VV1dZDVeZgdY0CGw9VFEwIUPEIjoXfhZq40d6uRe9YOe4AP4+/DHuDG",
	"gT3Gxj4nsBMYHS0tjED1Gb5C8iZGpAdQu/WVuucYwqoO+NWxNu62NPc1COfOI0mWgXTR7/xq5Vr9qmP1",
	"9v8g5eeMeck2vpDYnL9OKrc89aSce+rwyIeh/tDsgMY33pgKa1lHGiI8wcxawW9NNTqgdeiRMqA7dd3o",
	"gHZGm0bibhMDYcZRzAbO/DQ6iJkWoq3Oc8tdvrDxotFRrYYq2rA4g6Nfx84CuQb+aaPDVtpsqwcm//uB",
	"wvPZkv6+4b3FZ8mHzg/9bwAAAP//e42kJOFvAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
