// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	HealthResponseStatusHealthy   HealthResponseStatus = "healthy"
	HealthResponseStatusUnhealthy HealthResponseStatus = "unhealthy"
)

// Defines values for RankingResponsePeriodType.
const (
	RankingResponsePeriodTypeMonthly RankingResponsePeriodType = "monthly"
	RankingResponsePeriodTypeWeekly  RankingResponsePeriodType = "weekly"
	RankingResponsePeriodTypeYearly  RankingResponsePeriodType = "yearly"
)

// Defines values for GetClickedTagsParamsDays.
const (
	GetClickedTagsParamsDaysN1  GetClickedTagsParamsDays = 1
	GetClickedTagsParamsDaysN30 GetClickedTagsParamsDays = 30
	GetClickedTagsParamsDaysN7  GetClickedTagsParamsDays = 7
)

// Defines values for GetTrendingTagsParamsHours.
const (
	GetTrendingTagsParamsHoursN12 GetTrendingTagsParamsHours = 12
	GetTrendingTagsParamsHoursN24 GetTrendingTagsParamsHours = 24
	GetTrendingTagsParamsHoursN48 GetTrendingTagsParamsHours = 48
	GetTrendingTagsParamsHoursN6  GetTrendingTagsParamsHours = 6
)

// ApiKeyResponse APIキー発行レスポンス
type ApiKeyResponse struct {
	// CreatedAt 作成日時
	CreatedAt time.Time `json:"created_at"`

	// Description キーの説明
	Description *string `json:"description"`

	// ExpiresAt 有効期限
	ExpiresAt *time.Time `json:"expires_at"`

	// Id APIキーID
	Id openapi_types.UUID `json:"id"`

	// Key 生成されたAPIキー（この1回のみ表示）
	Key string `json:"key"`

	// Name キーの名前
	Name *string `json:"name"`
}

// ArchiveItem 日別エントリー数
type ArchiveItem struct {
	// Count その日のエントリー件数
	Count int `json:"count"`

	// Date 日付（YYYY-MM-DD形式）
	Date openapi_types.Date `json:"date"`
}

// ArchiveResponse 日別エントリー数一覧レスポンス
type ArchiveResponse struct {
	// Items 日別エントリー数一覧（日付降順）
	Items []ArchiveItem `json:"items"`
}

// ClickMetricsRequest クリック計測リクエスト
type ClickMetricsRequest struct {
	// EntryId エントリーID
	EntryId openapi_types.UUID `json:"entry_id"`

	// Referrer リファラーURL（オプション）
	Referrer *string `json:"referrer"`

	// UserAgent ユーザーエージェント（オプション）
	UserAgent *string `json:"user_agent"`
}

// ClickedTag クリックされたタグ（クリック数付き）
type ClickedTag struct {
	// ClickCount 集計期間内でのクリック数
	ClickCount int `json:"click_count"`

	// EntryCount このタグに紐づく総エントリー数
	EntryCount int `json:"entry_count"`

	// Id タグID
	Id openapi_types.UUID `json:"id"`

	// Name タグ名
	Name string `json:"name"`
}

// ClickedTagsResponse クリックされたタグ一覧レスポンス
type ClickedTagsResponse struct {
	// Days 集計対象日数
	Days int `json:"days"`

	// Tags クリックされたタグ一覧
	Tags []ClickedTag `json:"tags"`

	// Total 該当タグ総数
	Total int `json:"total"`
}

// CreateApiKeyRequest APIキー発行リクエスト
type CreateApiKeyRequest struct {
	// Description キーの説明（オプション）
	Description *string `json:"description"`

	// ExpiresAt 有効期限（オプション、将来の拡張用）
	ExpiresAt *time.Time `json:"expires_at"`

	// Name キーの名前（オプション、将来の管理用）
	Name *string `json:"name"`
}

// Entry はてなブックマークエントリー
type Entry struct {
	// BookmarkCount はてなブックマーク件数
	BookmarkCount int `json:"bookmark_count"`

	// CreatedAt レコード作成日時（ISO 8601形式）
	CreatedAt time.Time `json:"created_at"`

	// Excerpt 記事本文の抜粋
	Excerpt *string `json:"excerpt"`

	// FaviconUrl Favicon URL（FaviconプロキシAPI）
	FaviconUrl *string `json:"favicon_url,omitempty"`

	// Id エントリーID
	Id openapi_types.UUID `json:"id"`

	// PostedAt 記事の投稿日時（ISO 8601形式）
	PostedAt time.Time `json:"posted_at"`

	// Subject RSSフィードのsubject（画面非表示、内部利用）
	Subject *string `json:"subject"`

	// Tags エントリーに紐づくタグ一覧
	Tags []EntryTag `json:"tags"`

	// Title エントリーのタイトル
	Title string `json:"title"`

	// UpdatedAt レコード更新日時（ISO 8601形式）
	UpdatedAt time.Time `json:"updated_at"`

	// Url エントリーのURL
	Url string `json:"url"`
}

// EntryListResponse エントリー一覧レスポンス
type EntryListResponse struct {
	// Entries エントリー一覧
	Entries []Entry `json:"entries"`

	// Limit 1ページあたりの件数
	Limit int `json:"limit"`

	// Offset オフセット
	Offset int `json:"offset"`

	// Total 総件数（フィルタ適用後）
	Total int `json:"total"`
}

// EntryTag エントリーに紐づくタグ（スコア付き）
type EntryTag struct {
	// Score タグのスコア（Yahoo! キーフレーズ抽出APIから取得した重要度、0〜100）
	Score int `json:"score"`

	// TagId タグID
	TagId openapi_types.UUID `json:"tag_id"`

	// TagName タグ名
	TagName string `json:"tag_name"`
}

// ErrorResponse エラーレスポンス
type ErrorResponse struct {
	// Details 詳細情報（オプション）
	Details *map[string]interface{} `json:"details"`

	// Error エラーコード
	Error string `json:"error"`

	// Message エラーメッセージ
	Message string `json:"message"`
}

// HealthResponse ヘルスチェックレスポンス
type HealthResponse struct {
	// Database データベース接続状態
	Database *struct {
		// Connected 接続可否
		Connected *bool `json:"connected,omitempty"`

		// ResponseTimeMs レスポンスタイム（ミリ秒）
		ResponseTimeMs *float32 `json:"response_time_ms,omitempty"`
	} `json:"database,omitempty"`

	// Status ステータス
	Status HealthResponseStatus `json:"status"`

	// Timestamp チェック実行日時
	Timestamp time.Time `json:"timestamp"`
}

// HealthResponseStatus ステータス
type HealthResponseStatus string

// MetricsResponse メトリクス記録レスポンス
type MetricsResponse struct {
	// Message メッセージ
	Message string `json:"message"`

	// Success 成功フラグ
	Success bool `json:"success"`
}

// RankingEntry ランキングエントリー
type RankingEntry struct {
	// Entry はてなブックマークエントリー
	Entry Entry `json:"entry"`

	// Rank 順位
	Rank int `json:"rank"`
}

// RankingResponse ランキングレスポンス
type RankingResponse struct {
	// Entries ランキングエントリー一覧
	Entries []RankingEntry `json:"entries"`

	// Month 対象月（月次・週次ランキング時のみ）
	Month *int `json:"month"`

	// PeriodType ランキング期間種別
	PeriodType RankingResponsePeriodType `json:"period_type"`

	// Total 対象期間の総エントリー数
	Total int `json:"total"`

	// Week 対象週（週次ランキング時のみ、ISO週番号）
	Week *int `json:"week"`

	// Year 対象年
	Year int `json:"year"`
}

// RankingResponsePeriodType ランキング期間種別
type RankingResponsePeriodType string

// SearchResponse 検索結果レスポンス
type SearchResponse struct {
	// Entries 検索結果のエントリー一覧
	Entries []Entry `json:"entries"`

	// Limit 1ページあたりの件数
	Limit int `json:"limit"`

	// Offset オフセット
	Offset int `json:"offset"`

	// Query 検索キーワード
	Query string `json:"query"`

	// Total 検索結果の総件数
	Total int `json:"total"`
}

// TrendingTag トレンドタグ（出現回数付き）
type TrendingTag struct {
	// EntryCount このタグに紐づく総エントリー数
	EntryCount int `json:"entry_count"`

	// Id タグID
	Id openapi_types.UUID `json:"id"`

	// Name タグ名
	Name string `json:"name"`

	// OccurrenceCount 集計期間内での出現回数（エントリー数）
	OccurrenceCount int `json:"occurrence_count"`
}

// TrendingTagsResponse トレンドタグ一覧レスポンス
type TrendingTagsResponse struct {
	// Hours 集計対象時間
	Hours int `json:"hours"`

	// Tags トレンドタグ一覧
	Tags []TrendingTag `json:"tags"`

	// Total 該当タグ総数
	Total int `json:"total"`
}

// UnauthorizedError エラーレスポンス
type UnauthorizedError = ErrorResponse

// GetArchiveParams defines parameters for GetArchive.
type GetArchiveParams struct {
	// MinUsers 最低ブックマーク件数フィルタ
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`
}

// GetHotEntriesParams defines parameters for GetHotEntries.
type GetHotEntriesParams struct {
	// Date 取得対象日付（YYYYMMDD形式）
	Date string `form:"date" json:"date"`

	// MinUsers 最低ブックマーク件数（5/10/50/100/500/1000など）
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset オフセット（ページネーション用）
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetNewEntriesParams defines parameters for GetNewEntries.
type GetNewEntriesParams struct {
	// Date 取得対象日付（YYYYMMDD形式）
	Date string `form:"date" json:"date"`

	// MinUsers 最低ブックマーク件数（5/10/50/100/500/1000など）
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset オフセット（ページネーション用）
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetFaviconParams defines parameters for GetFavicon.
type GetFaviconParams struct {
	// Domain Faviconを取得するドメイン名
	Domain string `form:"domain" json:"domain"`
}

// GetMonthlyRankingParams defines parameters for GetMonthlyRanking.
type GetMonthlyRankingParams struct {
	// Year 対象年（YYYY形式）
	Year int `form:"year" json:"year"`

	// Month 対象月（MM形式、1-12）
	Month int `form:"month" json:"month"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetWeeklyRankingParams defines parameters for GetWeeklyRanking.
type GetWeeklyRankingParams struct {
	// Year 対象年（YYYY形式）
	Year int `form:"year" json:"year"`

	// Week 対象週（1-53、ISO週番号）
	Week int `form:"week" json:"week"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetYearlyRankingParams defines parameters for GetYearlyRanking.
type GetYearlyRankingParams struct {
	// Year 対象年（YYYY形式）
	Year int `form:"year" json:"year"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// SearchEntriesParams defines parameters for SearchEntries.
type SearchEntriesParams struct {
	// Q 検索キーワード
	Q string `form:"q" json:"q"`

	// MinUsers 最低ブックマーク件数フィルタ
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset オフセット（ページネーション用）
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetClickedTagsParams defines parameters for GetClickedTags.
type GetClickedTagsParams struct {
	// Days 集計対象日数（デフォルト 7日間）
	Days *GetClickedTagsParamsDays `form:"days,omitempty" json:"days,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetClickedTagsParamsDays defines parameters for GetClickedTags.
type GetClickedTagsParamsDays int

// GetTrendingTagsParams defines parameters for GetTrendingTags.
type GetTrendingTagsParams struct {
	// Hours 集計対象時間（デフォルト 24時間）
	Hours *GetTrendingTagsParamsHours `form:"hours,omitempty" json:"hours,omitempty"`

	// MinUsers 対象エントリーの最低ブックマーク件数
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetTrendingTagsParamsHours defines parameters for GetTrendingTags.
type GetTrendingTagsParamsHours int

// GetEntriesByTagParams defines parameters for GetEntriesByTag.
type GetEntriesByTagParams struct {
	// MinUsers 最低ブックマーク件数（5/10/50/100/500/1000など）
	MinUsers *int `form:"min_users,omitempty" json:"min_users,omitempty"`

	// Limit 取得件数
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset オフセット（ページネーション用）
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateApiKeyRequest

// RecordClickJSONRequestBody defines body for RecordClick for application/json ContentType.
type RecordClickJSONRequestBody = ClickMetricsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// APIキー発行
	// (POST /api-keys)
	CreateApiKey(w http.ResponseWriter, r *http.Request)
	// 日別エントリー数一覧取得
	// (GET /archive)
	GetArchive(w http.ResponseWriter, r *http.Request, params GetArchiveParams)
	// 人気順エントリー一覧取得
	// (GET /entries/hot)
	GetHotEntries(w http.ResponseWriter, r *http.Request, params GetHotEntriesParams)
	// 新着順エントリー一覧取得
	// (GET /entries/new)
	GetNewEntries(w http.ResponseWriter, r *http.Request, params GetNewEntriesParams)
	// Faviconプロキシ
	// (GET /favicons)
	GetFavicon(w http.ResponseWriter, r *http.Request, params GetFaviconParams)
	// ヘルスチェック
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// クリック計測
	// (POST /metrics/clicks)
	RecordClick(w http.ResponseWriter, r *http.Request)
	// 月次ランキング取得
	// (GET /rankings/monthly)
	GetMonthlyRanking(w http.ResponseWriter, r *http.Request, params GetMonthlyRankingParams)
	// 週次ランキング取得
	// (GET /rankings/weekly)
	GetWeeklyRanking(w http.ResponseWriter, r *http.Request, params GetWeeklyRankingParams)
	// 年次ランキング取得
	// (GET /rankings/yearly)
	GetYearlyRanking(w http.ResponseWriter, r *http.Request, params GetYearlyRankingParams)
	// キーワード検索
	// (GET /search)
	SearchEntries(w http.ResponseWriter, r *http.Request, params SearchEntriesParams)
	// クリックされたエントリーのタグ一覧取得
	// (GET /tags/clicked)
	GetClickedTags(w http.ResponseWriter, r *http.Request, params GetClickedTagsParams)
	// トレンドタグ一覧取得
	// (GET /tags/trending)
	GetTrendingTags(w http.ResponseWriter, r *http.Request, params GetTrendingTagsParams)
	// タグ別エントリー一覧取得
	// (GET /tags/{tag}/entries)
	GetEntriesByTag(w http.ResponseWriter, r *http.Request, tag string, params GetEntriesByTagParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// APIキー発行
// (POST /api-keys)
func (_ Unimplemented) CreateApiKey(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 日別エントリー数一覧取得
// (GET /archive)
func (_ Unimplemented) GetArchive(w http.ResponseWriter, r *http.Request, params GetArchiveParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 人気順エントリー一覧取得
// (GET /entries/hot)
func (_ Unimplemented) GetHotEntries(w http.ResponseWriter, r *http.Request, params GetHotEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 新着順エントリー一覧取得
// (GET /entries/new)
func (_ Unimplemented) GetNewEntries(w http.ResponseWriter, r *http.Request, params GetNewEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Faviconプロキシ
// (GET /favicons)
func (_ Unimplemented) GetFavicon(w http.ResponseWriter, r *http.Request, params GetFaviconParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ヘルスチェック
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// クリック計測
// (POST /metrics/clicks)
func (_ Unimplemented) RecordClick(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 月次ランキング取得
// (GET /rankings/monthly)
func (_ Unimplemented) GetMonthlyRanking(w http.ResponseWriter, r *http.Request, params GetMonthlyRankingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 週次ランキング取得
// (GET /rankings/weekly)
func (_ Unimplemented) GetWeeklyRanking(w http.ResponseWriter, r *http.Request, params GetWeeklyRankingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// 年次ランキング取得
// (GET /rankings/yearly)
func (_ Unimplemented) GetYearlyRanking(w http.ResponseWriter, r *http.Request, params GetYearlyRankingParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// キーワード検索
// (GET /search)
func (_ Unimplemented) SearchEntries(w http.ResponseWriter, r *http.Request, params SearchEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// クリックされたエントリーのタグ一覧取得
// (GET /tags/clicked)
func (_ Unimplemented) GetClickedTags(w http.ResponseWriter, r *http.Request, params GetClickedTagsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// トレンドタグ一覧取得
// (GET /tags/trending)
func (_ Unimplemented) GetTrendingTags(w http.ResponseWriter, r *http.Request, params GetTrendingTagsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// タグ別エントリー一覧取得
// (GET /tags/{tag}/entries)
func (_ Unimplemented) GetEntriesByTag(w http.ResponseWriter, r *http.Request, tag string, params GetEntriesByTagParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateApiKey operation middleware
func (siw *ServerInterfaceWrapper) CreateApiKey(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArchive operation middleware
func (siw *ServerInterfaceWrapper) GetArchive(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetArchiveParams

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArchive(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHotEntries operation middleware
func (siw *ServerInterfaceWrapper) GetHotEntries(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetHotEntriesParams

	// ------------- Required query parameter "date" -------------

	if paramValue := r.URL.Query().Get("date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "date", r.URL.Query(), &params.Date)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHotEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetNewEntries operation middleware
func (siw *ServerInterfaceWrapper) GetNewEntries(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetNewEntriesParams

	// ------------- Required query parameter "date" -------------

	if paramValue := r.URL.Query().Get("date"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "date"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "date", r.URL.Query(), &params.Date)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetNewEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetFavicon operation middleware
func (siw *ServerInterfaceWrapper) GetFavicon(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFaviconParams

	// ------------- Required query parameter "domain" -------------

	if paramValue := r.URL.Query().Get("domain"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "domain"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "domain", r.URL.Query(), &params.Domain)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "domain", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetFavicon(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RecordClick operation middleware
func (siw *ServerInterfaceWrapper) RecordClick(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RecordClick(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMonthlyRanking operation middleware
func (siw *ServerInterfaceWrapper) GetMonthlyRanking(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMonthlyRankingParams

	// ------------- Required query parameter "year" -------------

	if paramValue := r.URL.Query().Get("year"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "year", r.URL.Query(), &params.Year)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		return
	}

	// ------------- Required query parameter "month" -------------

	if paramValue := r.URL.Query().Get("month"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "month"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "month", r.URL.Query(), &params.Month)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "month", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMonthlyRanking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWeeklyRanking operation middleware
func (siw *ServerInterfaceWrapper) GetWeeklyRanking(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWeeklyRankingParams

	// ------------- Required query parameter "year" -------------

	if paramValue := r.URL.Query().Get("year"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "year", r.URL.Query(), &params.Year)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		return
	}

	// ------------- Required query parameter "week" -------------

	if paramValue := r.URL.Query().Get("week"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "week"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "week", r.URL.Query(), &params.Week)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "week", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWeeklyRanking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetYearlyRanking operation middleware
func (siw *ServerInterfaceWrapper) GetYearlyRanking(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetYearlyRankingParams

	// ------------- Required query parameter "year" -------------

	if paramValue := r.URL.Query().Get("year"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "year"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "year", r.URL.Query(), &params.Year)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "year", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetYearlyRanking(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SearchEntries operation middleware
func (siw *ServerInterfaceWrapper) SearchEntries(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchEntriesParams

	// ------------- Required query parameter "q" -------------

	if paramValue := r.URL.Query().Get("q"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SearchEntries(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetClickedTags operation middleware
func (siw *ServerInterfaceWrapper) GetClickedTags(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetClickedTagsParams

	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameter("form", true, false, "days", r.URL.Query(), &params.Days)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "days", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetClickedTags(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTrendingTags operation middleware
func (siw *ServerInterfaceWrapper) GetTrendingTags(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTrendingTagsParams

	// ------------- Optional query parameter "hours" -------------

	err = runtime.BindQueryParameter("form", true, false, "hours", r.URL.Query(), &params.Hours)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hours", Err: err})
		return
	}

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTrendingTags(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEntriesByTag operation middleware
func (siw *ServerInterfaceWrapper) GetEntriesByTag(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "tag" -------------
	var tag string

	err = runtime.BindStyledParameterWithOptions("simple", "tag", chi.URLParam(r, "tag"), &tag, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tag", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetEntriesByTagParams

	// ------------- Optional query parameter "min_users" -------------

	err = runtime.BindQueryParameter("form", true, false, "min_users", r.URL.Query(), &params.MinUsers)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_users", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEntriesByTag(w, r, tag, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api-keys", wrapper.CreateApiKey)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/archive", wrapper.GetArchive)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/entries/hot", wrapper.GetHotEntries)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/entries/new", wrapper.GetNewEntries)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/favicons", wrapper.GetFavicon)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/metrics/clicks", wrapper.RecordClick)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rankings/monthly", wrapper.GetMonthlyRanking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rankings/weekly", wrapper.GetWeeklyRanking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/rankings/yearly", wrapper.GetYearlyRanking)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/search", wrapper.SearchEntries)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags/clicked", wrapper.GetClickedTags)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags/trending", wrapper.GetTrendingTags)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/tags/{tag}/entries", wrapper.GetEntriesByTag)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9/VPUSrr/vzLffPfHGSYzMKhU3brFru451B5WCz13r+t62TDTQNaZZE6SUVmLqkni",
	"yyBwYFFRFEVUXgQFPHqUN+WPaTIvP/Ev3OruJCSZzmQG0fXuUnVKBibpfvrp5/k8r93nGpMUM1lRAIIi",
	"M23XGAnIWVGQAf7lR4HLKf2ixP8dpE5JkiihPyZFQQGCgj5y2WyaT3IKLwrRv8migP4GrnKZbBrgj+QV",
	"5sc/tv947vvTXR1/PnWSCTMZIMtcH2DamA7hMpfmUyFRCmV4WeaFvlD7mY7QJTDADIYZOdkPMhwa6DcS",
	"6GXamP8f3ac1Sr6Vo5iuLpNqZnBwMMykgJyU+Cwii2ljykuj5cVtqC1C/SXUt0MRNAfUXkN9G6ojpeuz",
	"xu0NqH6C6gxUV4vTS8Wx8d1Pj5hBmwLMivYs/wcwYM/Tds0ziz1maWqzPDsC9VdQ24D6Y6i/hdoGE2ay",
	"kpgFksITziYlwCkg1c0p1UPtfpwuFsaL9+eKUxoT3mcoE2fjiQgbi7CJczG2jUX//ZkJM72ilEHjMClO",
	"ARGFzwAmzCgDWfSKrEi80Md4meKd0mLHSnnpVfHBz65Zi9OvSveWShNrxjMdqitQvwf112hZegEz9S3U",
	"h6D2DOr3ob5UurvIhBkhl05zPehtRcoBCjHgapaXgExdfnF6yLi9UZyeqUyNe5ffGonFI82xc/HmtsSJ",
	"tsQJ3+UHUsCnauxhx0nXxCd6j4NjqdZkJNHTwkWak/FUJAbY3kgs3tySaD12/ATXk3QSksvxKdoWILmu",
	"mrR0d6ZYGIfqPaiNQHXGpmFvuwDVO1BdiRmPniC+qzvl2cXSi8297SEXdf093Wn+Mui2qWG5nmQK9Hp/",
	"p1EkcBlQQxqM8VFjaNQ12+8lrP6pUHs2G/oDGAjm9WCYkcBPOV4CKabtAoNZcwm/6FCCi/ZrYs/fQFJB",
	"xLVLyX7+MuhQQIYiJffnjMKcJYAFqC9Bfbt4b61a08ScQJEyqD6G6krx/hxirXuU3a33ZCB71YiVYSbD",
	"C3wml2HaWJtYXlBAH5CwfnEKoJK5u/Vgb7tw/vz585HOzsjJk8bHZ8b2mHcX93XbK9JMEEfNh8hCazDS",
	"H7z8mLm7ni/PLwRhGa+AjNzooHvbBcKbytRo5elNwg57pFqA7xSLQXu1nCRxA9XChgek8eR3aT55qRMo",
	"Ep+Uu8BPOSDThERbxWTrUFstLxaK66/Qr9oqWhTiSKGKF0BQpIFuGrh4GOGBmESCBcdbWDYC4id6Ii2x",
	"VEuEOxZrjbS0tLYmEi0tLMuy9UCMBHqBJAGJMj+a9h7UZokZ/LHrB4Qw2hLCbe0D1Beg/rYKWhQlK7dF",
	"o/2cAnrSYl+T+VVTUsxE0VJ5IEcFcKUewM3JQOrm+gBVGfV5BDjae/zvIv53HWoLhGHBdHaKf+fTaS6a",
	"aGKbmpoahiR703wFBaTOcX215cNGcKjtQG0NE73/LZL7rQdQHSWkeyAKTdHtA1SVRzeR6E3PVCbvGDdv",
	"QHUBI5ZraBdWJVqDoIqs1xcY7+AJ0CKgulx6Nw7VOaiOlT6MUdG2IZCkKwaayqMPsXgzQNYrAo6f6InE",
	"4qnmCNeSaI20xFtbYy2xYy116oOfgUNTGuNu0/adiJxT7uoPQOhT+pm2GMvWZczwHGHXLrp5XFusZH9c",
	"riFf9UFzihuQ/UTKWP1UfjOL3Ez3Ph6jbZzC9ckHoK9eTHcoWRWkhxlFVLh09ezll78YH++Q6UofxjzL",
	"aGZrC6NnJ/ECw4Rh1ozUfcM+ixUN+NiNqmCgttFoxDUPBsMD+OsOoU8goT80/72aWphXjbWbxcfI7yoO",
	"zxrbv5buLlKcocPz9OvycWsTWlqZLY3fpBBK8Ya9ABJsiqpk7BTCDhoyr0J1HqpLUJ80dU5/gm3lqgeZ",
	"qySsRxQvZTjpkj/o+w5N8YYTbBDO1wpvMWa9RYPrQ85Qd2+70HH2dOh4KxsLcpEPEP6Cq0kgZSnklBcf",
	"7G4OF6dfFSdvIZm8PV36ZdhjF8qL+fLSE6hN7H7cgepzqM78CfSE2s90VCaHS1ObSIpWZsoffi09vI55",
	"eBMzcNjkpDZRerexuzUM1fs4zzBVl48SZnq5y3xSFLpzEgX8fk++DBE/zvwN6/RrJNrah/YzHV4GRrks",
	"H70ci5oDy/+ZEjMcL/yHw6tz2VSJZ+qMnL+Oc5sVZT+hIruI9+9eaXHnQBLV3JhEyTmisFW0dJ09iz3t",
	"50TGobpiPrq3XSjd3ao8flZ5/ITE8ghkbt6o6ItG4SUFXixJ+hnv6jrR7EC58bPVri1yunYei23Pf+Ea",
	"IydFCTBtJxJ4WBzY1OuboecJ9iLPajBsD3bcOVg8eLCYezBLyNdwIDODPZ81ZvBina4GBlc/R4NX0qAO",
	"1hH3+AX+yzIdK9RlqBWgNlxZflDJz0B1yYUYNHnKZVN1YWbx0bvi5NoBJDzeKGZSgaeaGT92/UCNGp3B",
	"IicpfDINon1imhP6IldAT4TL8oFoQ3O3ySYR6pyYEPZaubDl1DmskYvNF/1s7w+8rNTyyt3poro8cTNa",
	"rnM0phFhpklyms/wFDmKQf2hGV2rGvbVb0N1pdrExxM0qy729sqAmiYhqYUtZPCwf2sPRPUOfPz50ocx",
	"QglyxkwAXYbaTkVF2Gh8GvEIN3ZVG3DxrS2wCLC4ZC/MVx58gv8AQMU+5QbSW+2Zf/BvgiI9RMVQYw6x",
	"t104z/WL4v8Lmb4rcuxf4d3cLN7+aNzaRGGHOgy1IWNs0vh0H/sbM5Vbo+V51dich3mVhfnpGMt6+IjA",
	"PcNdJWyMsYHOnYXdXzWQ3zcAXyyYN9flmCts7g5VMFx1J7p0vMTbFBCiA4Xj0/gjl0rx6HUufcbxCLHy",
	"3tD3bendWlG/YTx9ExgR4pKdrEgcj1x/JiMKSn8ok5OVUA8IxSKxOOI/D9Kp/YTzZS6ds8xHrJmN4TiK",
	"7nfscwRYFUI/TlgWzLVR/9X+Q8fJ9nMdp//Yfaqr63QXbfPtimENLs9ib3uLoJtrBqvKmOUkLgMUILWF",
	"0DJDROZsTpw/f/58Z+fJk4FWiKxznyqadHwPuLTSX0M89AcY3DagruJEJ4m5grI5CtfD0Ye7hRe+A/Up",
	"/GGj+PNc6f3D0u33xRvDlJqIIICkAihKTN4zxlaN8XknF1173iOKacAJJOFMltiNnIhuWh3AsyrLdXqK",
	"UX4G6kulhQkvsjfFHZDQmxax5TYnF3KZHhPdq9guK5ySoxrZDeRLExZhzgIB4dsFph9vFArcc4L1+aLL",
	"m7EfqMYkPgNkhctkaYve31YUG86OHG491yOS5rqdJNGk0q53+IvlrGnQUNy6UV58UBn5JUgs/bWzhlLi",
	"jF9IAklRSoFUSM4lk0CWe3Pp9AA92MLfU+S1MG7cnsG28CWKAwJF1ss5c+Da6tzFCZd4oc8vMYMg6C22",
	"yigWCUrGAGuUujw7iRMuUVK4T2/ufnRZvJjDbMcCfSE8qpmlrrXiWqLiXvSB/d+azGvMHXZtE8Urxqav",
	"mgQzEz5d2NsuFKcLxVezUN+q5N/gDy7qilMaKcV7ACsW97WPDscpCyReTHWTLwL4QAo+pcUVozDngKsB",
	"wElYQ/BS8KcrAFxKe0Br/9tq0KI73xYP0KxQXQmu9rBssKeISPObqpJHnkttLsO82nH2dCX/pnRvyRj7",
	"4GV6PTxHDPMjwdh45wp6WFrY41Ec5x6ao4erIguaQp0FnJSs4REUX0yX3j0r/TpefDJ9YGVyDVLd2PBv",
	"EFv+lAM0iCaMsQKnVYofamVuGtAZD7ft+NVTFW0oSCX0hw8WrJ6TgJDihT56vIrE4JVV/zEDVOPWZmns",
	"k/HoSc0C9VHB+MAxZpgRk8mcJAEhCRoq8Tt3Bod4XlZ60LAl3pCcOSvXVRQGl68dklbTnfSKXH3Jsn4x",
	"JwXVrae0yuQdF660NFC49iGsXmx0KtphFawTBypYE1b5Gx7kO4NkTuKVgbOIeODoZm3P0byh9jMdVsss",
	"Rsu8RmrJxouh4r01qC6UF18bKw8d9X5SSV0s3Vgwxgt2lQvmtb8IOM7VoZ4nGbLQX/870n6mI/IHMNAW",
	"GhBzUoTL8pFLYOCvIahNGOPLUFOhOu8pmOMh56E6BtWnaFr1Oh4bbZZAIrQUkCxxbmPsKfb1m8PrJd3B",
	"vNArWn3MHKnfmC9+b7Y5hc4BLlPVM8tYXVAhrILDUJ/D5u4Z1JdLQwVcah+3Sn5mnR23M+9u3SsuPCg+",
	"WiccqVHFrbLYJMMDtQnSlIy4qg13nTp7DvcwI5yYsliR5pPAVEJzOZ0d58w0+X5OXswCQRZzUhI0iVJf",
	"1HxJjqJn9wsg+5z4LZe8hOvbZzqYMHMZSLJp7JvYJhajWxYIXJZn2pjmJrapGakyp/RjIYuae4t/yYq0",
	"Roni5Bre3Ov7LdnahNk04ZIjBIXTi1BdNUVTXcLfL1jPLkB11HxcHbFL97geu2xJ83XysFF4X5kah9pE",
	"eeejcfvp7mYBS7OTlwiLcFd7RwqFqo6WD4YoIZCV34qpgTra4etrYqd1lQy6NR45uI58C2ZqnI0dGgme",
	"BndKI72nq4VE3kgGWlj20MgIbOfHSrZkJbysZg0rD4jISXxVcrRfsTM5brUuEiocsMu0XbgYZuRcJsMh",
	"z9TLRqtM1XaB4VIZXmAuopejHOlyRfT10fxi48aiHaz5ddpCbQIjKcJQUh6E6oKjNmBrF+nERSNZ+lh5",
	"ehOqy7vr81B963iwSje+A4rZj4s130ywyrh27G0Lyu9+/Nmvv8RZ77Fw3XKFTTjL8EJ3TgbY2u1vXgr0",
	"crm0wrQlnKY0wJJerNKjw5MYb7M1RWaONCdAc2xdqd1DTkTZqUCmKBIVshqU+0XFV42KI7eMlYe2/Htr",
	"etrE7uZmce0+7lAvuOvLoZOnzv4uHLIL0Pj3ve0hHx3zlXzs7VcmPxn5F04twBTgjJg6YoytlvWPtWzU",
	"d0D5XlRO2UFjTVUk5Nn9n/sHFDo73ccTaGpoVojchsmpke78NhvDJxqynKIACQ33P3/5S+ra8cHf0HLa",
	"jWHG3nYhEY2x0QQbjbHoB/7JYt/gpf8CGsGRQJeczlo7DUCb34rjKXPHE548iU9ZNlYPKZ7MCS63WAka",
	"fdSJAXbnEY1cM91ApZd1Z2P+aZhb3bRxhLqfgbo25lHzh1Woa6Wq3KgrgCsHR93i5FrpcZ6g7jcDsH8E",
	"V44A9nABNnYEsEcA+8UBtoWEybRZbI5Fq8+6f5MOsQWMB4Fmq+87AJf3M3v6ENRncbfGW6iuWE3m2gQN",
	"fr8Txb40CFl96e1nOkq/jpTuvnGhdV7Foe9zDDcfoD5HUnvlnbvuwWjwa44chL3VVE5Bbdi5FJLGp0Iv",
	"7oevE3x9uub7RVkx8+pe+A3WUD7D9YFoVuhzi5U9eA8vcNIAtR2EvHo1gnnU4Ns+qkz61Q19DCfL7kJ1",
	"CqHYkQMVqKWU4xgOpcwpfJpX9tWSdBj5KiXOFznmVBeru72gumKoc8aNxWJ+AWd9HE1lDsWqUivSpva7",
	"fpC8xHxB8+HphqMJ3Ovnxvr6NylbzV+RDdZG34HaBjkSsrs+aoyt1kwoUnsJHfImD8gKyJjCliEtYFF8",
	"WrVGZr6qu3ndc+wYYQJpD/OmEo3CHKnUQXWBHIo1JzVb8JC3uQzV5d2dx8brB5a18cf+LtwkhhvGvlT6",
	"nXIZwFdOv3tb82gX2WB2H4Wx9aJw9e0NDqUwRdLUCok0jslRq3GqtodkbLwrThegulKcLlQm73jal86d",
	"PhOKsayPn+QXbO2u3979ONpA3r2TkGr2vAWGpFbHkxmJBkWhZmdTHY4QaZuyA6kTJ06ccEQqcZatL65z",
	"9OB1dprVirwai8TiNSJN3M9XF5WxuDPYizca631e2ImDS2frXEOB55cM7Lxtnkd5s88JzszeURcaVMVk",
	"FtZ4ocfs4wxEHtKbCtWVSv7NPw18/oSJ/ZfCHtKQGoskmqltpzRCcX9rffDjoDLRfIQ+R+hz6OhDbaWu",
	"G33MxvJg9FFXYH7EbGJCaLKF06Dkw3v87wuov8CNY6NVvf1fFpTO4zV8C6DUcgig9CV1/kjp/0WUHkUi",
	"DSu9jI8i+Op67esOoL5F7kjBur5D1NrTWG9227u03LixWJy8Rb7Z2y5k+7p7+L7M3vYQuValdHcxIAVM",
	"DlDUWYHz6/enqdFPdSZ8HScEvBcmZXjBbgL/7LLb1+2FOqqwfRMVNs/xoCNQ/KzEDwWNnAlRgn8EDNEf",
	"STaUHIemd1uuzFQePsKXulBvvPMA5oIFaOSBeaheh9qwfaWDeQiC7g35Z0zR81rpxoJZSHPemYkvoMIU",
	"rpQLBeMfbyuTz4wdHb8yWnzwlFwFYcN1XfU2xw2FQWhbfaEgVtVbWHlfYqNRCB0r3p+rTN6p1fgw4INn",
	"x+wDkLHwsXAze7H2dYWHjmms65TgNxM+0e6QPAKOQ8oY+2v3ivPEUJWvhX86oEUxjwr5Ykvp0bvyzj8Q",
	"LOC2q0MFE7PRCp+VwifLKL1WRG0RtuVVe1Ry+qzydMvYnIfqon0JDdQmrNpO3YV751mxhpAEk01BkniL",
	"9ZUflFinomjK3GKDSWs4Fg/HW8Itxy8GnCPzyxlVy0Zt1+7/YMfUN4p91AOIR+D3OeDncyYyEOGuKVzf",
	"YNRxJr2u3qKq88I1ukC/RscnIagy+QtCU3XVyTFDfQfVhfKtJWP4nnmkzKx875eu97YLCtfXfZkHV7r7",
	"eVkRpQGn84biXD98NEPa3+JrxgLw0XkQGWtylsMVMFORFTxCPcFs8Xa+PHunnjuyjnpGjyLaf8ee0Zav",
	"Cc8EDEfK88NQfYEv8buNceUR1O58o64yBqKqw1kBNsPdxuQ+iH7hIpJHGUiX/U4Q7l9sXnWw2f5fVPwt",
	"a15zjK+ENecPSHFWJp9V8s8d3vEQ1B+bfa/4zhFT7SwbR9PrZ5hZy/ityXoHtA6sUQZ0p3TrHdDO9NJI",
	"3GlgIMw4CvjjXEq9g5iJFtrqPPeMFYrrr+od1WrdoQ2LcyL6TWzyyUXcz+sddr8ts3pgcgF88eVMWf9Y",
	"997i07yDFwf/NwAA//8XVx9pY20AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
